/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author cralves
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {

    //Variaveis que vão verificar se a janela esta aberta
    private boolean flagGUICadProdutos = false;
    private boolean flagGUIManutencaoProdutos = false;
    private boolean flagGUIManutencaoColaboradores = false;
    private boolean flagGUIColaborador = false;
    private boolean flagGUIManutencaoFornecedor = false;
    private boolean flagGUICadFornecedor = false;
    private boolean flagGUICadCliente = false;
    private boolean flagGUIManutencaoCliente = false;
    private boolean flagGUICompra = false;
    
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiColaborador = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiMenuProduto = new javax.swing.JMenuItem();
        jMenuColaborador = new javax.swing.JMenuItem();
        jMenufornecedor = new javax.swing.JMenuItem();
        jmiManuCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jdpAreaDeTrabalho.setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        jmiColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionarios.png"))); // NOI18N
        jmiColaborador.setText("Colaborador");
        jmiColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiColaboradorActionPerformed(evt);
            }
        });
        jmiColaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiColaboradorKeyPressed(evt);
            }
        });
        jMenu1.add(jmiColaborador);

        jmiFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido.png"))); // NOI18N
        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFornecedor);

        jmiProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cardapio.png"))); // NOI18N
        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmiProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiProdutoKeyPressed(evt);
            }
        });
        jMenu1.add(jmiProduto);
        jMenu1.add(jSeparator1);

        jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCliente);

        jMenuItem1.setText("Compra");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manutenção");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu2KeyPressed(evt);
            }
        });

        jmiMenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cardapio.png"))); // NOI18N
        jmiMenuProduto.setText("Produto");
        jmiMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMenuProdutoActionPerformed(evt);
            }
        });
        jmiMenuProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiMenuProdutoKeyPressed(evt);
            }
        });
        jMenu2.add(jmiMenuProduto);

        jMenuColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionarios.png"))); // NOI18N
        jMenuColaborador.setText("Colaborador");
        jMenuColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuColaboradorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuColaborador);

        jMenufornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido.png"))); // NOI18N
        jMenufornecedor.setText("Fornecedor");
        jMenufornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenufornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenufornecedor);

        jmiManuCliente.setText("Cliente");
        jmiManuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmiManuCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jMenu3.setText("Sair");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Métodos Criados
    private void abrirGUIColaborador() {
        //Criar um objeto e instanciar a classe
        GUICadColaborador gc = new GUICadColaborador();

        //Adicionando o objeto na Área de Trabalho
        jdpAreaDeTrabalho.add(gc);

        //Setando a visibilidade "true" para a janela surgir para o usuário
        gc.setVisible(true);
    }//fecha o método abrirGUIColadorador

    private void abrirGUICadProdutos() {

        if (!flagGUICadProdutos) { //not()! com false = true --> pergunta se o flag é verdadeiro
            GUICadProdutos gcp = new GUICadProdutos();
            jdpAreaDeTrabalho.add(gcp);
            gcp.setVisible(true);
            
            flagGUICadProdutos = true;
            
            gcp.addInternalFrameListener(this);
        }

    }//fecha abrirGUIcadProdutos
    
    private void abrirGUICadFornecedor() {

        if (!flagGUICadFornecedor) { //not()! com false = true --> pergunta se o flag é verdadeiro
            GUICadFornecedor gcf = new GUICadFornecedor();
            jdpAreaDeTrabalho.add(gcf);
            gcf.setVisible(true);
            
            flagGUICadFornecedor = true;
            
            gcf.addInternalFrameListener(this);
        }

    }
    private void abrirGUICadCliente() {

        if (!flagGUICadCliente) { //not()! com false = true --> pergunta se o flag é verdadeiro
            GUICadCliente gcf = new GUICadCliente();
            jdpAreaDeTrabalho.add(gcf);
            gcf.setVisible(true);
            
            flagGUICadCliente = true;
            
            gcf.addInternalFrameListener(this);
        }

    }
    private void abrirGUIManutencaoColaboradores(){
        if(!flagGUIManutencaoColaboradores){
            GUIManutencaoColaboradores gmc = new GUIManutencaoColaboradores(); 
            jdpAreaDeTrabalho.add(gmc);
            gmc.setVisible(true);
            
            flagGUIManutencaoColaboradores = true;
            gmc.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIManutencaoProdutos(){
        if(!flagGUIManutencaoProdutos){
            GUIManutencaoProdutos gmp = new GUIManutencaoProdutos(); 
            jdpAreaDeTrabalho.add(gmp);
            gmp.setVisible(true);
            
            flagGUIManutencaoProdutos = true;
            gmp.addInternalFrameListener(this);
        }
    }//fim abrirGUIManutencaoProdutos
    private void abrirGUIManutencaoFornecedor(){
        if(!flagGUIManutencaoFornecedor){
            GUIManutencaoFornecedor gmf = new GUIManutencaoFornecedor(); 
            jdpAreaDeTrabalho.add(gmf);
            gmf.setVisible(true);
            
            flagGUIManutencaoFornecedor = true;
            gmf.addInternalFrameListener(this);
        }
    }
    private void abrirGUIManutencaoCliente(){
        if(!flagGUIManutencaoCliente){
            GUIManutencaoCliente gmf = new GUIManutencaoCliente(); 
            jdpAreaDeTrabalho.add(gmf);
            gmf.setVisible(true);
            
            flagGUIManutencaoCliente = true;
            gmf.addInternalFrameListener(this);
        }
    }
    private void abrirGUICompra(){
        if(!flagGUICompra){
            GUICompra gmf = new GUICompra(); 
            jdpAreaDeTrabalho.add(gmf);
            gmf.setVisible(true);
            
            flagGUICompra = true;
            gmf.addInternalFrameListener(this);
        }
    }

    //Eventos Gerados
    private void jmiColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiColaboradorActionPerformed
        abrirGUIColaborador();
    }//GEN-LAST:event_jmiColaboradorActionPerformed

    private void jmiColaboradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiColaboradorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIColaborador();
        }
    }//GEN-LAST:event_jmiColaboradorKeyPressed

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        abrirGUICadProdutos();
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUICadProdutos();
        }
    }//GEN-LAST:event_jmiProdutoKeyPressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2KeyPressed

    private void jmiMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMenuProdutoActionPerformed
        abrirGUIManutencaoProdutos();
    }//GEN-LAST:event_jmiMenuProdutoActionPerformed

    private void jmiMenuProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiMenuProdutoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirGUIManutencaoProdutos();
        }
    }//GEN-LAST:event_jmiMenuProdutoKeyPressed

    private void jMenufornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenufornecedorActionPerformed
        abrirGUIManutencaoFornecedor();
    }//GEN-LAST:event_jMenufornecedorActionPerformed

    private void jMenuColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuColaboradorActionPerformed
        abrirGUIManutencaoColaboradores();
    }//GEN-LAST:event_jMenuColaboradorActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        abrirGUICadFornecedor();
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        abrirGUICadCliente();
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiManuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManuClienteActionPerformed
       abrirGUIManutencaoCliente();
    }//GEN-LAST:event_jmiManuClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       abrirGUICompra();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuColaborador;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenufornecedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiColaborador;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiManuCliente;
    private javax.swing.JMenuItem jmiMenuProduto;
    private javax.swing.JMenuItem jmiProduto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if(ife.getInternalFrame() instanceof GUICadProdutos){
            flagGUICadProdutos = false;
        }
        if(ife.getInternalFrame() instanceof GUIManutencaoProdutos){
            flagGUIManutencaoProdutos = false;
        }
        if(ife.getInternalFrame() instanceof GUIManutencaoProdutos){
            flagGUIManutencaoProdutos = false;
        }
        if(ife.getInternalFrame() instanceof GUICadColaborador){
            flagGUIColaborador = false;
        } 
        if(ife.getInternalFrame() instanceof GUIManutencaoColaboradores){
            flagGUIManutencaoColaboradores = false;
        }
        if(ife.getInternalFrame() instanceof GUICadFornecedor){
            flagGUICadFornecedor = false;
        } 
        if(ife.getInternalFrame() instanceof GUIManutencaoFornecedor){
            flagGUIManutencaoFornecedor = false;
        }
        if(ife.getInternalFrame() instanceof GUICadCliente){
            flagGUICadCliente = false;
        }
        if(ife.getInternalFrame() instanceof GUIManutencaoCliente){
            flagGUIManutencaoCliente = false;
        }
        if(ife.getInternalFrame() instanceof GUICompra){
            flagGUICompra = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {

    }
}
